---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured.
  template:
    src: "redis-{{ ansible_os_family }}.conf.j2"
    dest: "{{ redis_conf_path }}"
    backup: true
  notify: restart redis

# Setup/install tasks.
- name: Include Epel role
  include_role:
    name: geerlingguy.repo-epel
  when: "ansible_facts['os_family'] == 'RedHat'"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
