---
- name: Install apache
  apt:
    name:
      - apache2
      - apache2-utils
    state: present

- name: Create SSL directory
  file:
    path: "/etc/ssl/{{ project_name }}"
    state: directory

- name: Copy SSL Certs
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/{{ project_name }}/{{ item }}"
  with_items:
    - cert.pem
    - chain.pem
    - priv.key
  when: not letsencrypt

- name: Enable Apache mods.
  file:
    src: "/etc/apache2/mods-available/{{ item }}.load"
    dest: "/etc/apache2/mods-enabled/{{ item }}.load"
    state: link
    mode: 0644
  with_items:
      - rewrite
      - ssl
      - proxy
      - proxy_http
  notify: restart apache

- name: Configure vhost file
  template:
    src: staging.conf.j2
    dest: "/etc/apache2/sites-available/{{ project_name }}.conf"

- name: Disable default vhosts
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - 000-default.conf
    - default-ssl.conf
  notify: restart apache

- name: Enable the {{ project_name }} vhosts
  file:
    src: "/etc/apache2/sites-available/{{ project_name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ project_name }}.conf"
    state: link
    mode: 0644
  notify: restart apache
