---
# Used for RHEL/CentOS/Fedora only. Allows the use of different repos.
redis_enablerepo: epel
redis_port: 6379
redis_bind_interface: 0.0.0.0
# Require authentication to Redis with a password.
redis_requirepass: ""
