---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Populate service facts
    service_facts:

  - name: Assert that Kafka service is installed, running, and enabled
    assert:
      that:
          - "'kafka.service' in ansible_facts.services"
          - ansible_facts.services['kafka.service'].state == 'running'
          - ansible_facts.services['kafka.service'].status == 'enabled'
